os: osx
language: objective-c
osx_image: xcode9.2
cache:
  directories:
  - Carthage
xcode_project: RFYAudioKit.xcodeproj
xcode_scheme: RFYAudioKit
before_install:
  - brew install carthage || true
  - brew outdated carthage || brew upgrade carthage
before_script:
  - carthage bootstrap --platform iOS --no-use-binaries --cache-builds
script: xcodebuild build -project RFYAudioKit.xcodeproj -scheme RFYAudioKit